queue_rules:
  - name: default
    conditions:
        - "#check-failure=0"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
        - "-draft"
        - "#check-failure=0"
        - "#approved-reviews-by>=1"
    actions:
      queue:
        method: rebase
        name: default
