pull_request_rules:
  - name: Merge lockfile updates
    conditions:
      - "title=Update lockfile.json"
    actions:
      review:
        type: APPROVE
        message: Automatically approving lockfile updates
      merge:
        method: merge
  - name: Merge on approval
    conditions:
      - and:
        - "-draft"
        - "#approved-reviews-by>=1"
        - "#review-requested=0"
    actions:
      merge:
        method: rebase
