queue_rules:
  - name: default
    conditions:
        - "#check-failure=0"

pull_request_rules:
  - name: Merge lockfile updates
    conditions:
      - "title=Update lockfile.json"
    actions:
      merge:
        method: merge
        
  - name: Merge on approval
    conditions:
      - and:
        - "-draft"
        - "#check-failure=0"
        - "#approved-reviews-by>=1"
    actions:
      queue:
        method: rebase
        name: default
