; AUTO-GENERATED by scripts/sync_queries.py
; Edit only the LOCAL section in composed files.
; File: indents.scm
; === BEGIN CORE ===
"{" @indent.begin

"}" @indent.end

; === END CORE ===
; === BEGIN LOCAL ===
; === END LOCAL ===
