local filetypes = {
  bash = { 'sh' },
  bibtex = { 'bib' },
  c_sharp = { 'cs' },
  commonlisp = { 'lisp' },
  devicetree = { 'dts' },
  diff = { 'gitdiff' },
  eex = { 'eelixir' },
  embedded_template = { 'eruby' },
  facility = { 'fsd' },
  faust = { 'dsp' },
  git_config = { 'gitconfig' },
  git_rebase = { 'gitrebase' },
  glimmer = { 'handlebars', 'html.handlebars' },
  godot_resource = { 'gdresource' },
  haskell_persistent = { 'haskellpersistent' },
  janet_simple = { 'janet' },
  javascript = { 'javascriptreact', 'ecma', 'jsx' },
  linkerscript = { 'ld' },
  latex = { 'tex' },
  m68k = { 'asm68k' },
  markdown = { 'pandoc', 'quarto', 'rmd' },
  muttrc = { 'neomuttrc' },
  ocaml_interface = { 'ocamlinterface' },
  poe_filter = { 'poefilter' },
  properties = { 'jproperties' },
  qmljs = { 'qml' },
  scala = { 'sbt' },
  slang = { 'shaderslang' },
  sqp = { 'mysqp' },
  ssh_config = { 'sshconfig' },
  starlark = { 'bzl' },
  surface = { 'sface' },
  t32 = { 'trace32' },
  tcl = { 'expect' },
  tlaplus = { 'tla' },
  tsx = { 'typescriptreact', 'typescript.tsx' },
  typescript = { 'ts' },
  udev = { 'udevrules' },
  uxntal = { 'tal' },
  v = { 'vlang' },
  verilog = { 'sysverilog' },
  vhs = { 'tape' },
  xml = { 'xsd', 'xslt', 'svg' },
}

for lang, ft in pairs(filetypes) do
  vim.treesitter.language.register(lang, ft)
end
