[
  (for_in_statement)
  (for_statement)
  (while_statement)
  (arrow_function)
  (function)
  (function_declaration)
  (class_declaration)
  (method_definition)
  (do_statement)
  (with_statement)
  (switch_statement)
  (switch_case)
  (import_statement)
] @fold
