(type) @type
(statement) @statement
(number) @number
(comment) @comment
(string) @string
(label) @label
(keyword) @keyword
(boolean) @boolean
(float) @number
(constant) @identifier
(identifier) @constant
(punctuation) @punctuation
