(type) @type
(statement) @statement
(number) @number
(comment) @comment
(string) @string
(label) @label
(keyword) @keyword
"ret" @keyword.return
(boolean) @boolean
(float) @float
(constant) @identifier
(identifier) @constant
(symbol) @punctuation.delimiter
(bracket) @punctuation.bracket
