[
  (component_block)
  (css_declaration)
  (script_declaration)
  (element)
  (style_element)
  (script_element)
  (component_switch_statement)
  (field_declaration_list)
  (block)
  (interface_type)
  (comment)
  (const_declaration)
  (var_declaration)
] @fold
