; AUTO-GENERATED by scripts/sync_queries.py
; Edit only the LOCAL section in composed files.
; File: injections.scm
; === BEGIN CORE ===
(embedded_html
  (angled_bracket_fenced_text) @injection.content
  (#set! injection.language "html"))

(embedded_sql
  (_
    (paren_fenced_text) @injection.content)
  (#set! injection.language "sql"))

(embedded_js
  [
    (angled_bracket_fenced_text)
    (embedded_js_special_case)
  ] @injection.content
  (#set! injection.language "javascript"))

(embedded_xml
  (angled_bracket_fenced_text) @injection.content
  (#set! injection.language "xml"))

; === END CORE ===
; === BEGIN UDL ===
; Keywords, one of type language = "python", none of type codemode
; External method body injection based on [ Language = ... ]
(method_definition
  (method_keyword_external_language
    (typename) @_lang)
  (python_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "python" "Python" "PYTHON")
  (#set! injection.language "python"))

(method_definition
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "tsql" "TSQL" "tSQL" "tSql" "TSql")
  (#set! injection.language "tsql"))

(method_definition
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "ispl" "ISPL" "ISpl" "iSpl")
  (#set! injection.language "ispl"))

(trigger
  (method_keyword_external_language
    (typename) @_lang)
  (python_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "python" "Python" "PYTHON")
  (#set! injection.language "python"))

(trigger
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "tsql" "TSQL" "tSQL" "tSql" "TSql")
  (#set! injection.language "tsql"))

; A query must be of type %SQLQuery to have an SQL body, otherwise the body
; is empty
(query
  (return_type
    (typename
      (identifier) @_querytype
      (#any-of? @_querytype "%SqlQuery" "%sqlquery" "%SQLQUERY" "%Sqlquery" "%SQLQuery")))
  (external_method_body_content) @injection.content
  (#set! injection.language "sql")
  (#set! injection.include-children "true"))

; XDATA blocks:
; - xdata_any requires a keyword list that includes MimeType
; - xdata_xml allows an optional keyword list and defaults to XML
; ----------------------------
; XDATA injections (MimeType)
; ----------------------------
; text/markdown
;
(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/markdown" "\"text/markdown\"")
  (#set! injection.language "markdown"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/xml" "\"text/xml\"" "application/xml" "\"application/xml\"")
  (#set! injection.language "xml"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/html" "\"text/html\"")
  (#set! injection.language "html"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "application/json" "\"application/json\"")
  (#set! injection.language "json"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/yaml" "\"text/yaml\"" "application/yaml" "\"application/yaml\"")
  (#set! injection.language "yaml"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/css" "\"text/css\"")
  (#set! injection.language "css"))

; -----------------------------------------
; XDATA default (no MimeType): XML fallback
; -----------------------------------------
(xdata
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#set! injection.language "xml"))

; Storage definition is XML
(storage
  (external_method_body_content) @injection.content
  (#set! injection.language "xml")
  (#set! injection.include-children "true"))

; === END UDL ===
; === BEGIN LOCAL ===
; Keywords, one of type language = "python", none of type codemode
; External method body injection based on [ Language = ... ]
(method_definition
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "python" "Python" "PYTHON")
  (#set! injection.language "python"))

(method_definition
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "tsql" "TSQL" "tSQL" "tSql" "TSql")
  (#set! injection.language "tsql"))

(method_definition
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "ispl" "ISPL" "ISpl" "iSpl")
  (#set! injection.language "ispl"))

(trigger
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "python" "Python" "PYTHON")
  (#set! injection.language "python"))

(trigger
  (method_keyword_external_language
    (typename) @_lang)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_lang "tsql" "TSQL" "tSQL" "tSql" "TSql")
  (#set! injection.language "tsql"))

; A query must be of type %SQLQuery to have an SQL body, otherwise the body
; is empty
(query
  (return_type
    (typename
      (identifier) @_querytype
      (#any-of? @_querytype "%SqlQuery" "%sqlquery" "%SQLQUERY" "%Sqlquery" "%SQLQuery")))
  (external_method_body_content) @injection.content
  (#set! injection.language "sql")
  (#set! injection.include-children "true"))

; XDATA blocks:
; - xdata_any requires a keyword list that includes MimeType
; - xdata_xml allows an optional keyword list and defaults to XML
; ----------------------------
; XDATA injections (MimeType)
; ----------------------------
; text/markdown
;
(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/markdown" "\"text/markdown\"")
  (#set! injection.language "markdown"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/xml" "\"text/xml\"" "application/xml" "\"application/xml\"")
  (#set! injection.language "xml"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/html" "\"text/html\"")
  (#set! injection.language "html"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "application/json" "\"application/json\"")
  (#set! injection.language "json"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/yaml" "\"text/yaml\"" "application/yaml" "\"application/yaml\"")
  (#set! injection.language "yaml"))

(xdata
  (xdata_keyword_mimetype
    (typename) @_mt)
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#any-of? @_mt "text/css" "\"text/css\"")
  (#set! injection.language "css"))

; -----------------------------------------
; XDATA default (no MimeType): XML fallback
; -----------------------------------------
(xdata
  (external_method_body_content) @injection.content
  (#set! injection.include-children "true")
  (#set! injection.language "xml"))

; Storage definition is XML
(storage
  (external_method_body_content) @injection.content
  (#set! injection.language "xml")
  (#set! injection.include-children "true"))

; === END LOCAL ===
