[
  (block)
  (comptime_block)
  (defer_block)
  (suspend_block)
  (resume_block)
  (if_expression)
  (switch_block)
  (for_expression)
  (test_expression)
  (struct_expression)
  (anonymous_struct_enum)
  (anonymous_array_expr)
  (union_expression)
  (enum_expression)
] @fold
