name: Check loading of syntax files

on: [push, pull_request]

jobs:
  luacheck:
    name: Check Query Files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get install -y npm
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          npm i -g tree-sitter
          sudo cp ~/.npm-global/bin/tree-sitter /usr/bin/
          wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          chmod u+x nvim.appimage
          mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter/start
          ln -s $(pwd) ~/.local/share/nvim/site/pack/nvim-treesitter/start

      - name: Compile parsers
        run: ./nvim.appimage --headless -c "TSInstallSync all" -c "q"

      - name: Check query files
        run: ./nvim.appimage --headless -c "luafile ./scripts/check-queries.lua" -c "q"

      - uses: actions/upload-artifact@v2
        with:
          name: parsers
          path: parser/*
