name: Tests

on:
  # push:
  #   branches:
  #     - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  check_compilation:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/setup-action/cli@v1

      - name: Test Dependencies
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/plenary.nvim/start
          cd ~/.local/share/nvim/site/pack/plenary.nvim/start
          git clone https://github.com/nvim-lua/plenary.nvim
          curl -L https://github.com/theHamsta/highlight-assertions/releases/download/v0.1.6/highlight-assertions_v0.1.6_x86_64-unknown-linux-gnu.tar.gz | tar -xz
          cp highlight-assertions /usr/local/bin

      - name: Install and prepare Neovim
        env:
          NVIM_TAG: nightly
          TREE_SITTER_CLI_TAG: v0.20.8
        run: |
          bash ./scripts/ci-install.sh

      - name: Setup Parsers Cache
        id: parsers-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/nvim/site/parser/
            ~/AppData/Local/nvim-data/site/parser/
          key: parsers-${{ join(matrix.*, '-') }}-${{ hashFiles(
            './lua/nvim-treesitter/install.lua',
            './lua/nvim-treesitter/parsers.lua') }}

      - name: Compile parsers
        run: nvim -l ./scripts/install-parsers.lua

      - name: Tests
        run: PATH=/usr/local/bin:$PATH ./scripts/run_tests.sh
