name: Make Parser Update PR

on:
  push:
    branches:
      - master

jobs:
  update-parsers:
    name: Update parsers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get install -y jq
          wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          chmod u+x nvim.appimage
          mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter/start
          ln -s $(pwd) ~/.local/share/nvim/site/pack/nvim-treesitter/start

      - name: Update parsers
        run: |
          ./nvim.appimage --headless -c "luafile ./scripts/write-lockfile.lua" -c "q"
          # Pretty print
          cp lockfile.json /tmp/lockfile.json
          cat /tmp/lockfile.json | jq --sort-keys > lockfile.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update lockfile.json
          title: Update lockfile.json
          branch: update-lockfile-pr
