name: Update parsers

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  update-parsers:
    name: Update parsers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.TOKEN_ID }}
          private-key: ${{ secrets.TOKEN_PRIVATE_KEY }}

      - name: Prepare
        env:
          NVIM_TAG: nightly
        run: |
          bash scripts/ci-install.sh
          wget --directory-prefix="$BIN_DIR" https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
          (cd "$BIN_DIR"; unzip stylua*.zip)

      - name: Update parsers
        run: |
          nvim -l ./scripts/update-parsers.lua

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: "nvim-treesitter-bot[bot] <157957100+nvim-treesitter-bot[bot]@users.noreply.github.com>"
          commit-message: "bot(parsers): update ${{ env.UPDATED_PARSERS }}"
          title: "Update parsers: ${{ env.UPDATED_PARSERS }}"
          body: "[beep boop](https://github.com/peter-evans/create-pull-request)"
          branch: update-parsers-pr
          base: ${{ github.head_ref }}

      - name: Enable Pull Request Automerge
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr merge --rebase --auto update-parsers-pr
