name: Make Parser Update PR

on: push

jobs:
  update-parsers:
    name: Update parsers
    runs-on: ubuntu-latest
    #if: github.ref == 'master'
    steps:
      - uses: actions/checkout@v1

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          chmod u+x nvim.appimage
          mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter/start
          ln -s $(pwd) ~/.local/share/nvim/site/pack/nvim-treesitter/start

      # inspired by nvim-lspconfigs
      - name: Update parsers
        run: |
          ./nvim.appimage --headless -c "luafile ./scripts/write-lockfile.lua" -c "q"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
